# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: david@historymakers.com.br
author_name: David Bonfim
contract_name: algo_cdt_stable
deployment_language: python
preset_name: starter
project_name: CDTBRL

