# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: david@historymakers.com.br
author_name: David Bonfim
contract_name: cdt_revenue_orchestrator
preset_name: production
project_name: RevenueOrchestrator

